insert into up_attraction
(NAME, DATE_CREATE, DATE_UPDATE)
values
	('Паласио Бароло', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Базилика Дель Сантисимо Сакраменто', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Парк Трес де Фебреро', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Берлинский собор', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Бранденбургские ворота', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Красная ратуша', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Национальный музей Таланга', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Музей Тай Хуа', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Музей морских раковин', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Тауэр', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Церковь Святой Маргариты', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Ботанические сады Кью', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Вацлавская площадь', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Карлова площадь', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Карлов мост', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Площадь Ливов', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Рижский замок', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Национальная опера', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Афинский акрополь', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Башня ветров', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Театр Диониса', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Ворота турецкой крепости', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Заповедник "Большой Утриш"', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Ореховая роща', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Пласа-Майор', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Площадь Пуэрта-дель-Соль', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Площадь Сибилис', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Собор Святого Марка', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Дворец дожей', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Старая библиотека Сан-Марко', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Дворец-крепость Алькасар', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Севильский кафедральный собор', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Торре-дель-Оро', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Дворец Потала', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Площадь Баркор', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Монастырь Джоканг', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Площадь Джемаа аль-Фна', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Ворота Баб-Агнау', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Мечеть ибн Юсуфа', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Храм Ад-Дэйр', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Мавзолей Эль-Хазне', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Гробницы в южной части города', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Римский форум', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Пантеон', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Пьяцца Навона', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into up_product_attraction
(PRODUCT_ID, ATTRACTION_ID)
values
	(1, 1),
	(1, 2),
	(1, 3),
	(2, 4),
	(2, 5),
	(2, 6),
	(3, 7),
	(3, 8),
	(3, 9),
	(4, 10),
	(4, 11),
	(4, 12),
	(5, 13),
	(5, 14),
	(5, 15),
	(6, 16),
	(6, 17),
	(6, 18),
	(7, 19),
	(7, 20),
	(7, 21),
	(8, 22),
	(8, 23),
	(8, 24),
	(9, 25),
	(9, 26),
	(9, 27),
	(10, 28),
	(10, 29),
	(10, 30),
	(11, 31),
	(11, 32),
	(11, 33),
	(12, 34),
	(12, 35),
	(12, 36),
	(13, 37),
	(13, 38),
	(13, 39),
	(14, 40),
	(14, 41),
	(14, 42),
	(15, 43),
	(15, 44),
	(15, 45);
